### ISSUE TITLE
Needed to extract Comments from a pdf

### ISSUE THREAD

**Issue by dummifiedme** [needleworm/img_crop_from_PDF#1]
Does it work for that purpose?
I tried running the code, but nothing seems to happen except for a folder that is created

**Comment by needleworm** [comment]
> Does it work for that purpose?
> I tried running the code, but nothing seems to happen except for a folder that is created

It works for my PDF files now.
It does not recognize any vector type figures.
Would you send me the file which you tried?

**Comment by dummifiedme** [comment]
I don't exactly know if I am doing it right. I am assuming it extracts all the comments highlights and maybe even the drawings?
Here is the test file I used.
[test.pdf](https://github.com/needleworm/img_crop_from_PDF/files/5792526/test.pdf)

**Comment by needleworm** [comment]
Highlights or comments are not considered as image data. They're not extracted with this code.
It works for non-vector type images or figures only.
Thanks.

**Comment by dummifiedme** [comment]
Okay . Thanks
Can you direct me to a place where I can find such a code? I tried finding it but most of them focus on text extraction than comments.
If you are aware of some project that extracts comments, please help.

**Comment by needleworm** [comment]
I don't know such project.
By the way, if comments or highlights have specific patterns such as color, you can simply extract them with OpenCv library.
